server:
  port: 8091
  servlet:
    context-path: /monitoring-tool-tracking-ms
spring:
  datasource:
    url: jdbc:h2:file:./target/h2db/db/technical-test
    driverClassName: org.h2.Driver
    username:
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
logging:
  level:
    root: INFO

user:
  service:
    url: http://localhost:8090


